### ISSUE TITLE
htmlwidgets adaptation of fishTones.js for Shiny apps

### ISSUE THREAD

**Issue by wyu** [Genentech/fishtones-js#2]
Thanks for releasing this fantastic package for public usage! They are very well done. We'd love to use them inside our Shiny app for the visualization of MS data. 

Are you aware of any effort to adopt this library to Shiny framework in the way of htmlWidgets? 

Thanks!
Wen

**Comment by alexmasselot** [comment]
Thanks for the comments.
I've not heard on any thing in the Shiny direction, but woud love to see something around that

Alex
